---
- name: install netcat
  sudo: yes
  yum:
    name: nmap-ncat
    state: present
  tags:
    - zookeeper

- name: install wait script
  sudo: yes
  copy:
    src: zookeeper-wait-for-listen.sh
    dest: /usr/local/bin
    mode: u=rwx,g=rx,o=rx
  tags:
    - zookeeper

- name: generate default env file
  sudo: yes
  template:
    src: zookeeper-env.j2 
    dest: "/etc/default/{{ zookeeper_service }}"
  notify: 
    - restart zookeeper
  tags: 
    - zookeeper

- name: zookeeper latency check script
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: zookeeper_latency_check.sh.j2
      dest: /usr/local/bin/zookeeper_latency_check.sh
  tags:
    - zookeeper

- name: generate systemd service file 
  sudo: yes
  template:
    src: zookeeper-service.j2 
    dest: "/usr/lib/systemd/system/{{ zookeeper_service }}.service"
  notify: 
    - register zookeeper service
    - reload systemd daemon 
  tags: 
    - zookeeper

- name: install zookeeper scripts
  sudo: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items:
    - src: zookeeper_check.sh
      dest: /usr/local/bin
  tags:
    - zookeeper

- name: zookeper latency scripts and libs
  sudo: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
  with_items:
    - src: zk-latencies.py
      dest: /usr/local/bin
      mode: u=rwx
    - src: zookeeper.so
      dest: /usr/local/lib
      mode: u=rw
    - src: libzookeeper_mt.so.2
      dest: /usr/local/lib
      mode: u=rw
    - src: zkclient.py
      dest: /usr/local/bin
      mode: u=rw
  when: "'zookeeper_servers' in {{ group_names }}"
  notify:
    - reload consul
  tags:
    - zookeeper

- name: generate zookeeper consul services
  sudo: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: zk-consul.json.j2
      dest: /etc/consul/zk-consul.json
  notify:
    - reload consul
  tags:
    - zookeeper

- meta: flush_handlers
